# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('patient_id', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
